source 'http://rubygems.org'

gem 'rails',            '3.0.3'
gem 'mysql2',           '0.2.6'
gem 'unicorn',          '3.3.0'
gem 'sunspot',          '1.2.1'
gem 'sunspot_rails',    '1.2.1'
gem 'haml',             '3.0.25'
gem 'will_paginate', '~> 3.0.beta'
gem 'dynamic_form',     '1.1.3'
gem 'database_cleaner', '0.6.0'